### ISSUE TITLE
How to get current status of shutter

### ISSUE THREAD

**Issue by ckohrt** [ChrisHanuta/node-red-contrib-velux#18]
Hi,
I want to get the current status of the shutter with node id 0 which I think I could get with the API node. I want to use this information to stop movement when I press the up or down button (normal 2 channel light switch button in the wall) again while movement (I only have two buttons - not three). So I took an inject node (extended an example doing this given in another issue https://github.com/PLCHome/node-red-contrib-velux/issues/12) and connected it to the API node (which has empty fields which cannot be set -see other issue https://github.com/PLCHome/node-red-contrib-velux/issues/11).

The command is described in the PDF API documentation on page 62 and here https://github.com/PLCHome/velux-klf200-api/blob/master/lib/klf.js

From the latter I can get:
Command				          |Data 1 - 2 |Data 3   |Data 4 |Data 5     		   |Data 6 – 7
GW_COMMAND_RUN_STATUS_NTF |SessionID  |StatusID |Index  |NodeParameter |ParameterValue
    Data 8    |Data 9      |Data 10 - 13
    RunStatus |StatusReply |InformationCode

I want to get the RunStatus value, which can be:
0 EXECUTION_COMPLETED Execution is completed with no errors.
1 EXECUTION_FAILED Execution has failed. (Get specifics in the following error code)
2 EXECUTION_ACTIVE

I tried to put this into the string which is sent to the KLF200 via API node:

msg.payload={"apiText":"GW_COMMAND_RUN_STATUS_NTF","statusID":0,"index":0,"nodeParameter":0,"parameterValue":0,"runStatus":0,"informationCode":0}

The result is from the debug node if i click inject:
Velux API Error: timeout GW_COMMAND_RUN_STATUS_NTF
    at Object.<anonymous> (/data/node_modules/velux-klf200-api/lib/net.js:190:19)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)

So, any chance to get the information during shutter movement?

In node red there is displayed that the shutter is moving, but I think I can't use this information since there is no output of this. But this would also help...

Thanks,
Christian

PS
Really nice work!!!!!

**Comment by ckohrt** [comment]
...just tried the "Velux Nodes" node with input 
`velux:load:id:0:valuetype:CURRENT:`
and I can get back GW_GET_NODE_INFORMATION_NTF which I am after. So hopefully this also works during movement, then I am happy. Kids are sleeping so I will try it tomorrow..
[flows (8).zip](https://github.com/PLCHome/node-red-contrib-velux/files/8128615/flows.8.zip)
.

**Comment by ckohrt** [comment]
Ok, hat funktioniert. Mit zwei Tasten kann ich nun:

- kurzer Klick rauf/runter: Rollo Fährt ganz hoch/runter
- kurzer Klick rauf/runter während der Fahrt: Rollo stoppt
- langer Klick rauf/runter: Rollo Fährt hoch/runter bis Taste los gelassen wird

**Comment by ckohrt** [comment]
Zusätzliche Info: Es war mir nicht möglich während der Bewegung des Rollos die Status Info Position zu bekommen. Leider...
